{
  "uid" : "464d7be0cb9735a3",
  "name" : "test_registration_new_user_awdev_t506[{'name': '\\u0410\\u043d\\u0438\\u043a\\u0438\\u0442\\u0430 \\u0417\\u0438\\u043d\\u043e\\u0432\\u044c\\u0435\\u0432\\u0438\\u0447 \\u0414\\u0430\\u043d\\u0438\\u043b\\u043e\\u0432', 'email': 'ljubov_68@example.com', 'phone': '+380636706722'}-1111]",
  "fullName" : "tests.ui.test_registration_new_user.TestRegistrationUser#test_registration_new_user_awdev_t506",
  "historyId" : "75ad2caa16de077b2f53525a49a01b39",
  "time" : {
    "start" : 1723548586142,
    "stop" : 1723548586142,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/127.0.6533.99/chromedriver unexpectedly exited. Status code was: 127",
  "statusTrace" : "pytestconfig = <_pytest.config.Config object at 0x7ff00e7935b0>\nrequest = <SubRequest 'set_driver' for <Function test_registration_new_user_awdev_t506[{'name': '\\u0410\\u043d\\u0438\\u043a\\u0438\\...\\u0447 \\u0414\\u0430\\u043d\\u0438\\u043b\\u043e\\u0432', 'email': 'ljubov_68@example.com', 'phone': '+380636706722'}-1111]>>\n\n    @pytest.fixture(autouse=True)\n    def set_driver(pytestconfig, request):\n        driver = None\n        browser = pytestconfig.getoption(\"--browser_name\")\n        if browser == \"chrome\":\n            chromedriver_autoinstaller.install()\n            options = webdriver.ChromeOptions()\n            options.add_argument(\"--headless\")\n            options.add_argument(\"--no-sandbox\")\n            options.add_argument(\"--disable-dev-shm-usage\")\n            options.add_argument(\"--window-size=1920,1080\")\n>           driver = webdriver.Chrome(options=options)\n\ntests/ui/conftest.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n../local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py:55: in __init__\n    self.service.start()\n../local/lib/python3.10/site-packages/selenium/webdriver/common/service.py:102: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.chrome.service.Service object at 0x7ff00be22da0>\n\n    def assert_process_still_running(self) -> None:\n        \"\"\"Check if the underlying process is still running.\"\"\"\n        return_code = self.process.poll()\n        if return_code:\n>           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\nE           selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/127.0.6533.99/chromedriver unexpectedly exited. Status code was: 127\n\n../local/lib/python3.10/site-packages/selenium/webdriver/common/service.py:115: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "set_driver",
    "time" : {
      "start" : 1723548586142,
      "stop" : 1723548586526,
      "duration" : 384
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/127.0.6533.99/chromedriver unexpectedly exited. Status code was: 127\n\n",
    "statusTrace" : "  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/usr/workspace/tests/ui/conftest.py\", line 23, in set_driver\n    driver = webdriver.Chrome(options=options)\n  File \"/usr/local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/usr/local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 55, in __init__\n    self.service.start()\n  File \"/usr/local/lib/python3.10/site-packages/selenium/webdriver/common/service.py\", line 102, in start\n    self.assert_process_still_running()\n  File \"/usr/local/lib/python3.10/site-packages/selenium/webdriver/common/service.py\", line 115, in assert_process_still_running\n    raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "stepsCount" : 0,
    "hasContent" : true
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1723548567725,
      "stop" : 1723548567802,
      "duration" : 77
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  }, {
    "name" : "pytestconfig",
    "time" : {
      "start" : 1723548567802,
      "stop" : 1723548567802,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  }, {
    "name" : "set_env_settings",
    "time" : {
      "start" : 1723548567802,
      "stop" : 1723548567803,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "tests.ui"
  }, {
    "name" : "suite",
    "value" : "test_registration_new_user"
  }, {
    "name" : "subSuite",
    "value" : "TestRegistrationUser"
  }, {
    "name" : "host",
    "value" : "118a8be09252"
  }, {
    "name" : "thread",
    "value" : "1-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.ui.test_registration_new_user"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "code",
    "value" : "1111"
  }, {
    "name" : "user",
    "value" : "{'name': 'Аникита Зиновьевич Данилов', 'email': 'ljubov_68@example.com', 'phone': '+380636706722'}"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "464d7be0cb9735a3.json",
  "parameterValues" : [ "1111", "{'name': 'Аникита Зиновьевич Данилов', 'email': 'ljubov_68@example.com', 'phone': '+380636706722'}" ]
}